version: '3.9'
services: 
  app:
    build: 
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
    networks:
      - delovaya
    ports: 
      - 3080:3000
    volumes: 
      - ".:/home/docker/app"
  db:
    environment: 
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
    image: postgres:13.2
    networks:
      - delovaya
    volumes: 
      - delovaya_db:/var/lib/postgresql/data

networks: 
  delovaya:

volumes: 
  delovaya_db: